name: Terraform and Terragrunt

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::984220190731:role/github-actions-devops-capstone
          aws-region: us-east-1

      - name: Run Terragrunt Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: 1.16.0
          tg_version: 1.1.4
          tg_dir: "./"
          tg_command: "plan"