name: Terraform and Terragrunt

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::984220190731:role/github-actions-devops-capstone
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: ${{ inputs.tf_version }}

      - name: Run Terragrunt Plan
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: ${{ inputs.tg_version }}
          tf_path: /home/runner/workflow/terraform # Points directly to your TF binary
          tg_dir: ${{ inputs.working_dir }}
          tg_command: "plan"
